### ISSUE TITLE
Have python give intelligible errors when config is missing/wrong

### ISSUE THREAD

**Issue by jkamins7** [HopkinsIDD/COVIDScenarioPipeline#32]

**Comment by jkamins7** [comment]
```python3 COVIDScenarioPipeline/simulate.py -c config.yml -s None
Traceback (most recent call last):
  File "COVIDScenarioPipeline/simulate.py", line 67, in <module>
    simulate()
  File "/home/jkaminsky/.local/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/jkaminsky/.local/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/jkaminsky/.local/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jkaminsky/.local/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "COVIDScenarioPipeline/simulate.py", line 25, in simulate
    config.set_file(config_file)
  File "/home/jkaminsky/.local/lib/python3.7/site-packages/confuse.py", line 993, in set_file
    self.set(ConfigSource(load_yaml(filename), filename))
  File "/home/jkaminsky/.local/lib/python3.7/site-packages/confuse.py", line 142, in __init__
    super(ConfigSource, self).__init__(value)
TypeError: 'NoneType' object is not iterable
```

**Comment by samshah** [comment]
what command line args did you give? if the file doesn't exist, it should error:
```
(python_venv)  07266e72b620:~/src$ python simulate.py  -c filedoesnotexist.yml
Usage: simulate.py [OPTIONS]
Try 'simulate.py --help' for help.

Error: Invalid value for '-c' / '--config': Path 'filedoesnotexist.yml' does not exist.
```

```
(python_venv)  07266e72b620:~/src$ CONFIG_PATH=filedoesnotexist.yml python simulate.py
Usage: simulate.py [OPTIONS]
Try 'simulate.py --help' for help.

Error: Invalid value for '-c' / '--config': Path 'filedoesnotexist.yml' does not exist.
```

**Comment by jkamins7** [comment]
i'm now unable to replicate, so probably this was user error
